name: CI

on: [push, pull_request_target]

jobs:
  build-test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        PHP_VERSION: [ "7.4", "8.0", "8.1" ]
    env:
      PHP_VERSION: ${{ matrix.php_version }}

    steps:
      - uses: actions/checkout@v2
      - uses: php-actions/composer@v6
        with:
          version: 1
      - uses: php-actions/phpunit@v3
