name: CI

on: [push, pull_request]

jobs:
  build-test:
    runs-on: ubuntu-24.04
    strategy:
      matrix:
        ROBO_VERSION: [ "4.0", "5.0" ]
        PHP_VERSION: [ "8.2", "8.3" ]
        include:
          - ROBO_VERSION: "4.0"
            PHP_VERSION: "8.0"
          - ROBO_VERSION: "4.0"
            PHP_VERSION: "8.1"
    env:
      PHP_VERSION: ${{ matrix.PHP_VERSION }}
    steps:
      - name: clone
        uses: actions/checkout@v4
      - name: test
        run: |
          docker compose up -d
          docker compose exec -u root -T php composer require consolidation/robo:~${{ matrix.ROBO_VERSION }} 
          docker compose exec -u root -T php phpunit
